-- ================================================================
-- SHELFY: CONSOLIDATED RANKING FIX
-- Recreates missing ranking_historico_manual and updates RPCs
-- ================================================================

BEGIN;

-- 1. Create storage for historical rankings
CREATE TABLE IF NOT EXISTS public.ranking_historico_manual (
    id_hist          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_distribuidor  BIGINT NOT NULL REFERENCES distribuidores(id_distribuidor),
    anio             INT NOT NULL,
    mes              INT NOT NULL,
    nombre_vendedor  TEXT NOT NULL,
    aprobadas        INT DEFAULT 0,
    destacadas       INT DEFAULT 0,
    puntos           INT DEFAULT 0,
    updated_at       TIMESTAMPTZ DEFAULT NOW(),
    
    UNIQUE(id_distribuidor, anio, mes, nombre_vendedor)
);

-- 2. Restore Historical Data (Jan/Feb 2026 for T&H)
INSERT INTO public.ranking_historico_manual (id_distribuidor, anio, mes, nombre_vendedor, aprobadas, destacadas, puntos)
VALUES 
(3, 2026, 1, 'Jesus Grimaldi', 136, 11, 147),
(3, 2026, 1, 'Ricardo Lauro', 115, 1, 116),
(3, 2026, 1, 'Romina Cigarreros', 99, 9, 108),
(3, 2026, 1, 'Monchi Ayala', 74, 12, 86),
(3, 2026, 1, 'David Brunetto', 62, 0, 62),
(3, 2026, 1, 'Alejandro', 53, 5, 58),
(3, 2026, 1, 'Claudio', 51, 5, 56),
(3, 2026, 1, 'Monchi', 35, 4, 39),
(3, 2026, 1, 'ricardo romero', 31, 4, 35),
(3, 2026, 1, 'Luciano', 31, 4, 35),
(3, 2026, 2, 'Monchi', 149, 15, 164),
(3, 2026, 2, 'Romina', 64, 2, 66),
(3, 2026, 2, 'Miguel Juan', 63, 1, 64),
(3, 2026, 2, 'Miguel Angel', 60, 1, 61),
(3, 2026, 2, 'Alejandro', 59, 2, 61),
(3, 2026, 2, 'Ivan', 41, 10, 51),
(3, 2026, 2, 'Artur', 34, 0, 34),
(3, 2026, 2, 'Luciano', 21, 3, 24),
(3, 2026, 2, 'Romina Perez', 20, 1, 21),
(3, 2026, 2, 'Guille', 20, 0, 20)
ON CONFLICT DO NOTHING;

-- 3. Update fn_dashboard_ranking (Now includes sucursal logic)
CREATE OR REPLACE FUNCTION fn_dashboard_ranking(
    p_dist_id BIGINT,
    p_periodo TEXT DEFAULT 'mes',
    p_top INT DEFAULT 15
)
RETURNS TABLE (
    vendedor TEXT,
    sucursal TEXT,
    aprobadas BIGINT,
    destacadas BIGINT,
    rechazadas BIGINT,
    puntos BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    WITH stats AS (
        -- Data from live exhibitions
        SELECT 
            CASE 
                WHEN UPPER(i.id_vendedor_erp) IN ('IVAN SOTO', 'IVAN WUTRICH', 'MATIAS WUTRICH') THEN i.nombre_integrante
                ELSE COALESCE(NULLIF(i.id_vendedor_erp, ''), i.nombre_integrante)
            END as vendedor_name,
            COALESCE(l.label, 'Sin Sucursal') AS sucursal_label,
            COUNT(*) FILTER (WHERE LOWER(e.estado) IN ('aprobado', 'aprobada')) as aprob,
            COUNT(*) FILTER (WHERE LOWER(e.estado) IN ('destacada', 'destacado')) as dest,
            COUNT(*) FILTER (WHERE LOWER(e.estado) IN ('rechazado', 'rechazada')) as rech,
            (COUNT(*) FILTER (WHERE LOWER(e.estado) IN ('aprobado', 'aprobada')) * 1 +
             COUNT(*) FILTER (WHERE LOWER(e.estado) IN ('destacada', 'destacado')) * 2) as pts
        FROM exhibiciones e
        LEFT JOIN integrantes_grupo i ON i.id_integrante = e.id_integrante
        LEFT JOIN locations l ON l.location_id = i.location_id
        WHERE (p_dist_id = 0 OR e.id_distribuidor = p_dist_id)
          AND (
            (p_periodo = 'mes' AND e.timestamp_subida >= date_trunc('month', NOW() AT TIME ZONE 'America/Argentina/Buenos_Aires')) OR
            (p_periodo = 'hoy' AND e.timestamp_subida >= date_trunc('day', NOW() AT TIME ZONE 'America/Argentina/Buenos_Aires')) OR
            (p_periodo = 'semana' AND e.timestamp_subida >= date_trunc('week', NOW() AT TIME ZONE 'America/Argentina/Buenos_Aires')) OR
            (p_periodo = 'ayer' AND e.timestamp_subida >= date_trunc('day', (NOW() AT TIME ZONE 'America/Argentina/Buenos_Aires') - interval '1 day') AND e.timestamp_subida < date_trunc('day', NOW() AT TIME ZONE 'America/Argentina/Buenos_Aires')) OR
            (LENGTH(p_periodo) = 7 AND p_periodo ~ '^\d{4}-\d{2}$' AND TO_CHAR(e.timestamp_subida AT TIME ZONE 'America/Argentina/Buenos_Aires', 'YYYY-MM') = p_periodo)
          )
        GROUP BY 1, 2

        UNION ALL

        -- Data from historical manual records (legacy or recovery data)
        SELECT h.nombre_vendedor AS vendedor_name,
               'Histórico' AS sucursal_label,
               h.aprobadas::BIGINT AS aprob,
               h.destacadas::BIGINT AS dest,
               0::BIGINT AS rech,
               h.puntos::BIGINT AS pts
        FROM ranking_historico_manual h
        WHERE (p_dist_id = 0 OR h.id_distribuidor = p_dist_id)
          AND (
            CASE
              WHEN p_periodo = 'hoy' THEN FALSE
              WHEN p_periodo = 'mes' THEN
                h.anio = CAST(TO_CHAR(NOW() AT TIME ZONE 'America/Argentina/Buenos_Aires', 'YYYY') AS INT)
                AND h.mes = CAST(TO_CHAR(NOW() AT TIME ZONE 'America/Argentina/Buenos_Aires', 'MM') AS INT)
              WHEN LENGTH(p_periodo) = 7 AND p_periodo ~ '^\d{4}-\d{2}$' THEN
                h.anio = CAST(SPLIT_PART(p_periodo, '-', 1) AS INT)
                AND h.mes = CAST(SPLIT_PART(p_periodo, '-', 2) AS INT)
              ELSE TRUE
            END
          )
    )
    SELECT s.vendedor_name AS vendedor,
           s.sucursal_label AS sucursal,
           SUM(s.aprob)::BIGINT AS aprobadas,
           SUM(s.dest)::BIGINT AS destacadas,
           SUM(s.rech)::BIGINT AS rechazadas,
           SUM(s.pts)::BIGINT AS puntos
    FROM stats s
    GROUP BY s.vendedor_name, s.sucursal_label
    HAVING SUM(s.pts) > 0
    ORDER BY puntos DESC, aprobadas DESC
    LIMIT p_top;
END;
$$;

COMMIT;
