-- ================================================================
-- MÓDULO ERP COMPLETO: TABLAS + ANALÍTICA (Fase E)
-- ================================================================
-- INSTRUCCIONES: Correr este script en el SQL Editor de Supabase.

-- 1. Mapeo de Empresas (Nombre en Excel -> ID en CenterMind)
CREATE TABLE IF NOT EXISTS erp_empresa_mapping (
    nombre_erp        TEXT PRIMARY KEY,
    id_distribuidor   BIGINT NOT NULL REFERENCES distribuidores(id_distribuidor)
);

-- 2. Padrón de Clientes (Raw)
CREATE TABLE IF NOT EXISTS erp_clientes_raw (
    id_distribuidor       BIGINT NOT NULL REFERENCES distribuidores(id_distribuidor),
    id_cliente_erp_local  TEXT NOT NULL,
    id_cliente_interno    TEXT,
    nombre_cliente        TEXT,
    nombre_fantasia       TEXT,
    vendedor_erp          TEXT,
    sucursal_erp          TEXT,
    lat                   NUMERIC,
    lon                   NUMERIC,
    forma_pago            TEXT,
    updated_at            TIMESTAMPTZ DEFAULT NOW(),
    
    PRIMARY KEY (id_distribuidor, id_cliente_erp_local)
);

-- 3. Informe de Ventas (Raw)
CREATE TABLE IF NOT EXISTS erp_ventas_raw (
    id_distribuidor    BIGINT NOT NULL REFERENCES distribuidores(id_distribuidor),
    nro_documento      TEXT NOT NULL,
    fecha_factura      DATE NOT NULL,
    codi_cliente       TEXT NOT NULL,
    nomcli             TEXT,
    importe_neto       NUMERIC(15,2) DEFAULT 0,
    importe_final      NUMERIC(15,2) DEFAULT 0,
    unidades           NUMERIC(15,2) DEFAULT 0,
    vendedor_erp       TEXT,
    sucursal_erp       TEXT,
    tipo_documento     TEXT,
    created_at         TIMESTAMPTZ DEFAULT NOW(),
    
    PRIMARY KEY (id_distribuidor, nro_documento)
);

-- 4. Configuración de Alertas de Crédito
CREATE TABLE IF NOT EXISTS erp_config_alertas (
    id_config        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_distribuidor  BIGINT NOT NULL REFERENCES distribuidores(id_distribuidor) UNIQUE,
    limite_dinero    NUMERIC(15,2) DEFAULT 500000,
    limite_cbte      INTEGER DEFAULT 5,
    limite_dias      INTEGER DEFAULT 30,
    activo           BOOLEAN DEFAULT TRUE,
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Resumen de Deuda consolidada (Capa de Acceso Rápido)
CREATE TABLE IF NOT EXISTS erp_deuda_clientes (
    id_deuda              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_distribuidor       BIGINT NOT NULL REFERENCES distribuidores(id_distribuidor),
    id_cliente_erp_local  TEXT NOT NULL,
    nombre_cliente        TEXT,
    vendedor_erp          TEXT,
    saldo_total           NUMERIC(15,2) DEFAULT 0,
    cant_cbte             INTEGER DEFAULT 0,
    antiguedad_max_dias   INTEGER DEFAULT 0,
    alerta_texto          TEXT,
    fecha_snapshot        TIMESTAMPTZ DEFAULT NOW(),
    
    UNIQUE(id_distribuidor, id_cliente_erp_local)
);

-- Índices para mejorar velocidad
CREATE INDEX IF NOT EXISTS idx_ventas_fecha ON erp_ventas_raw(id_distribuidor, fecha_factura);
CREATE INDEX IF NOT EXISTS idx_ventas_cliente ON erp_ventas_raw(id_distribuidor, codi_cliente);
CREATE INDEX IF NOT EXISTS idx_clientes_erp_mapping ON erp_clientes_raw(id_distribuidor, id_cliente_erp_local);

-- ────────────────────────────────────────────────────────────────
-- FUNCIONES RPC (API)
-- ────────────────────────────────────────────────────────────────

-- 1. KPIs de Recaudación (Soporta filtrado por vendedor opcional)
CREATE OR REPLACE FUNCTION fn_reporte_recaudacion_kpis(
    p_dist_id  BIGINT,
    p_desde    DATE,
    p_hasta    DATE,
    p_vendedor TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_venta_total NUMERIC;
    v_clientes    INT;
    v_volumen     NUMERIC;
    v_tickets     INT;
    v_top         JSONB;
    v_bottom      JSONB;
BEGIN
    SELECT COALESCE(SUM(importe_final), 0) INTO v_venta_total FROM erp_ventas_raw
    WHERE id_distribuidor = p_dist_id 
      AND fecha_factura BETWEEN p_desde AND p_hasta
      AND (p_vendedor IS NULL OR vendedor_erp = p_vendedor);

    SELECT COUNT(DISTINCT codi_cliente) INTO v_clientes FROM erp_ventas_raw
    WHERE id_distribuidor = p_dist_id 
      AND fecha_factura BETWEEN p_desde AND p_hasta
      AND (p_vendedor IS NULL OR vendedor_erp = p_vendedor);

    SELECT COALESCE(SUM(unidades), 0) INTO v_volumen FROM erp_ventas_raw
    WHERE id_distribuidor = p_dist_id 
      AND fecha_factura BETWEEN p_desde AND p_hasta
      AND (p_vendedor IS NULL OR vendedor_erp = p_vendedor);

    SELECT COUNT(*) INTO v_tickets FROM erp_ventas_raw
    WHERE id_distribuidor = p_dist_id 
      AND fecha_factura BETWEEN p_desde AND p_hasta
      AND (p_vendedor IS NULL OR vendedor_erp = p_vendedor);

    SELECT jsonb_agg(sub) INTO v_top FROM (
        SELECT descrip_comp as articulo, SUM(unidades) as cantidad FROM erp_ventas_raw
        WHERE id_distribuidor = p_dist_id 
          AND fecha_factura BETWEEN p_desde AND p_hasta
          AND (p_vendedor IS NULL OR vendedor_erp = p_vendedor)
        GROUP BY descrip_comp ORDER BY cantidad DESC LIMIT 10
    ) sub;

    SELECT jsonb_agg(sub) INTO v_bottom FROM (
        SELECT descrip_comp as articulo, SUM(unidades) as cantidad FROM erp_ventas_raw
        WHERE id_distribuidor = p_dist_id 
          AND fecha_factura BETWEEN p_desde AND p_hasta
          AND (p_vendedor IS NULL OR vendedor_erp = p_vendedor)
        GROUP BY descrip_comp ORDER BY cantidad ASC LIMIT 5
    ) sub;

    RETURN jsonb_build_object(
        'venta_total', v_venta_total,
        'clientes_activos', v_clientes,
        'volumen_articulos', v_volumen,
        'ticket_promedio', CASE WHEN v_tickets > 0 THEN v_venta_total / v_tickets ELSE 0 END,
        'top_articulos', COALESCE(v_top, '[]'::jsonb),
        'bottom_articulos', COALESCE(v_bottom, '[]'::jsonb),
        'puntos_mapa', (SELECT COUNT(*) FROM erp_clientes_raw WHERE id_distribuidor = p_dist_id AND lat IS NOT NULL AND (p_vendedor IS NULL OR vendedor_erp = p_vendedor))
    );
END;
$$;

-- 2. Detalle de Recaudación (Soporta filtrado por vendedor opcional)
CREATE OR REPLACE FUNCTION fn_reporte_recaudacion_detallada(
    p_dist_id  BIGINT,
    p_desde    DATE,
    p_hasta    DATE,
    p_vendedor TEXT DEFAULT NULL
)
RETURNS TABLE (
    cliente      TEXT,
    comprobante  TEXT,
    tipo         TEXT,
    pago         TEXT,
    monto        NUMERIC
)
LANGUAGE sql
AS $$
    SELECT 
        v.nomcli as cliente,
        v.nro_documento as comprobante,
        v.tipo_documento as tipo,
        c.forma_pago as pago,
        v.importe_final as monto
    FROM erp_ventas_raw v
    LEFT JOIN erp_clientes_raw c ON v.id_distribuidor = c.id_distribuidor AND v.codi_cliente = c.id_cliente_erp_local
    WHERE v.id_distribuidor = p_dist_id 
      AND v.fecha_factura BETWEEN p_desde AND p_hasta
      AND (p_vendedor IS NULL OR v.vendedor_erp = p_vendedor)
    ORDER BY v.fecha_factura DESC;
$$;

-- 3. Clientes Muertos (Inactivos)
CREATE OR REPLACE FUNCTION fn_reporte_clientes_muertos(
    p_dist_id BIGINT,
    p_dias    INT
)
RETURNS TABLE (
    nombre          TEXT,
    ultima_compra   DATE,
    dias_inactivo   INT
)
LANGUAGE sql
AS $$
    WITH ultimas_compras AS (
        SELECT codi_cliente, MAX(fecha_factura) as max_fecha
        FROM erp_ventas_raw
        WHERE id_distribuidor = p_dist_id
        GROUP BY codi_cliente
    )
    SELECT 
        c.nombre_cliente as nombre,
        u.max_fecha as ultima_compra,
        (CURRENT_DATE - u.max_fecha)::INT as dias_inactivo
    FROM erp_clientes_raw c
    JOIN ultimas_compras u ON c.id_cliente_erp_local = u.codi_cliente
    WHERE c.id_distribuidor = p_dist_id
      AND u.max_fecha < (CURRENT_DATE - p_dias)
    ORDER BY dias_inactivo DESC;
$$;

-- Valores por defecto para distribuidores
INSERT INTO erp_config_alertas (id_distribuidor)
SELECT id_distribuidor FROM distribuidores
ON CONFLICT (id_distribuidor) DO NOTHING;
