-- ================================================================
-- Capa 5: Módulo ERP - Scaffolding (Multi-tenant)
-- ================================================================

-- 1. Mapeo de Empresas ERP a Distribuidoras locales
-- Permite que el usuario configure "Nombre en Excel" -> "ID en Shelfy"
CREATE TABLE IF NOT EXISTS erp_empresa_mapping (
    id_mapping       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_erp       TEXT NOT NULL UNIQUE, -- Ej: 'TABACO & HNOS S.R.L'
    id_distribuidor  BIGINT NOT NULL REFERENCES distribuidores(id_distribuidor),
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Clientes RAW (Maestro de Clientes del ERP)
CREATE TABLE IF NOT EXISTS erp_clientes_raw (
    id_cliente_erp        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_distribuidor       BIGINT NOT NULL REFERENCES distribuidores(id_distribuidor),
    id_cliente_interno    TEXT, -- 'IdClienteInterno' en Excel
    id_cliente_erp_local  TEXT NOT NULL, -- 'idcliente' en Excel
    nombre_cliente        TEXT, -- 'nomcli'
    nombre_fantasia       TEXT, -- 'fantacli'
    vendedor_erp          TEXT, -- 'd_vendedor'
    sucursal_erp          TEXT, -- 'dssucur'
    fecha_ultima_compra   DATE,
    created_at            TIMESTAMPTZ DEFAULT NOW(),
    
    -- Unicidad por distribuidor y ID de cliente del ERP
    UNIQUE(id_distribuidor, id_cliente_erp_local)
);

-- 3. Ventas RAW (Transacciones del ERP)
CREATE TABLE IF NOT EXISTS erp_ventas_raw (
    id_venta_erp      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_distribuidor   BIGINT NOT NULL REFERENCES distribuidores(id_distribuidor),
    nro_documento     TEXT NOT NULL, -- 'nro_documento' (PK lógica para evitar duplicados)
    fecha_factura     DATE NOT NULL,
    codi_cliente      TEXT NOT NULL, -- Relaciona con erp_clientes_raw.id_cliente_erp_local
    nomcli            TEXT,
    importe_neto      NUMERIC(15,2),
    importe_final     NUMERIC(15,2),
    unidades          NUMERIC(15,2),
    vendedor_erp      TEXT,
    sucursal_erp      TEXT,
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    
    UNIQUE(id_distribuidor, nro_documento)
);

-- 4. Índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_erp_ventas_cliente ON erp_ventas_raw(id_distribuidor, codi_cliente);
CREATE INDEX IF NOT EXISTS idx_erp_clientes_nombre ON erp_clientes_raw(id_distribuidor, nombre_cliente);

-- Inserción inicial para T&H (según ejemplo)
-- Nota: id_distribuidor=3 es 'Real Distribucion - T&H' según logs previos.
INSERT INTO erp_empresa_mapping (nombre_erp, id_distribuidor) 
VALUES ('TABACO & HNOS  S.R.L', 3)
ON CONFLICT (nombre_erp) DO UPDATE SET id_distribuidor = EXCLUDED.id_distribuidor;
