-- ================================================================
-- Capa 5: Módulo ERP - Motor de Alertas (Fase C)
-- ================================================================

-- 1. Configuración de Límites de Crédito por Distribuidor
CREATE TABLE IF NOT EXISTS erp_config_alertas (
    id_config        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_distribuidor  BIGINT NOT NULL REFERENCES distribuidores(id_distribuidor) UNIQUE,
    limite_dinero    NUMERIC(15,2) DEFAULT 500000,
    limite_cbte      INTEGER DEFAULT 5,
    limite_dias      INTEGER DEFAULT 30,
    activo           BOOLEAN DEFAULT TRUE,
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Resumen de Deuda por Cliente (Tabla de Consulta Rápida)
-- Se alimenta de erp_ventas_raw y erp_clientes_raw
CREATE TABLE IF NOT EXISTS erp_deuda_clientes (
    id_deuda              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_distribuidor       BIGINT NOT NULL REFERENCES distribuidores(id_distribuidor),
    id_cliente_erp_local  TEXT NOT NULL, -- 'codi_cliente'
    nombre_cliente        TEXT,
    vendedor_erp          TEXT,
    saldo_total           NUMERIC(15,2) DEFAULT 0,
    cant_cbte             INTEGER DEFAULT 0,
    antiguedad_max_dias   INTEGER DEFAULT 0,
    alerta_texto          TEXT,
    fecha_snapshot        TIMESTAMPTZ DEFAULT NOW(),
    
    UNIQUE(id_distribuidor, id_cliente_erp_local)
);

-- 3. Inserción de valores por defecto para distribuidores existentes
INSERT INTO erp_config_alertas (id_distribuidor)
SELECT id_distribuidor FROM distribuidores
ON CONFLICT (id_distribuidor) DO NOTHING;
